services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - sweettweet

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

  user:
    build:
      context: ../
      dockerfile: cmd/user/Dockerfile
    command: /app/cmd/user/user
    depends_on:
      - mongo
      - redis
    env_file:
      - ../.env
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - backend
    ports:
      - "8082:8082"

  auth:
    build:
      context: ../
      dockerfile: cmd/auth/Dockerfile
    command: /app/cmd/auth/auth
    depends_on:
      - db
    env_file:
      - ../.env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - backend
    ports:
      - "8081:8081"

  api:
    build:
      context: ../
      dockerfile: cmd/api/Dockerfile
    command: /app/cmd/api/api
    depends_on:
      - auth
      - user
    env_file:
      - ../.env
    environment:
      AUTH_SERVICE_ADDR: ${AUTH_SERVICE_ADDR}
      USER_SERVICE_ADDR: ${USER_SERVICE_ADDR}
      GIN_PORT: ${GIN_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  pgdata:
  mongo-data:
  redis-data:

networks:
  sweettweet:
  backend: